default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # This must match what POSTGRES_USER was set to in docker-compose.yml.
  username: postgres

  # This must be 127.0.0.1 and not localhost.
  host: 127.0.0.1

development:
  <<: *default
  database: helloworld_db_development

test:
  <<: *default
  database: helloworld_db_test

production:
  <<: *default
  database: helloworld_db_production
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>